name: OppsBot
namespace: bf-OppsBot
defaultLanguage: en
nluThreshold: 0.75
timezoneOffset: 0
allowContextualQuestions: false
instance:
  name: Default Instance
  host: 'http://rasa:5005'
  projectId: tT3zW2Xh8foja5Pyt
